#ifndef INCLUDED_TEST_RESOURCES_H
#define INCLUDED_TEST_RESOURCES_H

#ifndef WISEKMA_KNOWLEDGE
# define WISEKMA_KNOWLEDGE "@wisekma_KNOWLEDGE@"
#endif

#ifndef IZENECMA_KNOWLEDGE
# define IZENECMA_KNOWLEDGE "@izenecma_KNOWLEDGE@"
#endif

#ifndef IZENEJMA_KNOWLEDGE
# define IZENEJMA_KNOWLEDGE "@izenejma_KNOWLEDGE@"
#endif

#ifndef LID_DB
# define LID_DB "@ilplib_LANGUAGEIDENTIFIER_DB@"
#endif

#endif // INCLUDED_TEST_RESOURCES_H
