#ifndef IDMLIB_VERSION_H
#define IDMLIB_VERSION_H

#define IDMLIB_VERSION_MAJOR @CPACK_PACKAGE_VERSION_MAJOR@
#define IDMLIB_VERSION_MINOR @CPACK_PACKAGE_VERSION_MINOR@
#define IDMLIB_VERSION_PATCH @CPACK_PACKAGE_VERSION_PATCH@

#define IDMLIB_VERSION "@CPACK_PACKAGE_VERSION_MAJOR@.@CPACK_PACKAGE_VERSION_MINOR@.@CPACK_PACKAGE_VERSION_PATCH@"

#endif